# Generated by Django 5.0.4 on 2024-04-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
