# Generated by Django 5.0.4 on 2024-04-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.IntegerField(choices=[('#F98866', 'petal'), ('#FF420E', 'poppy'), ('#80BD9E', 'stem'), ('#89DA59', 'green')]),
        ),
    ]
