# Generated by Django 5.0.4 on 2024-04-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('#F98866', 'petal'), ('#FF420E', 'poppy'), ('#80BD9E', 'stem'), ('#89DA59', 'green')], max_length=7),
        ),
    ]
