# Generated by Django 5.0.4 on 2024-04-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
